### ISSUE TITLE
Saving a df

### ISSUE THREAD

**Issue by AtaTrkgl** [synw/df#3]
Is there a way of converting a df to a csv file or some other way of saving it.

**Comment by caseycrogers** [comment]
Hey @AtaTrkgl Are you still interested in this feature? I currently have a fork of DF that I could add save functionality too. I'm waiting on review from synw to merge my fork back into this repo, but if you need this feature you could use my fork in the meantime (once I add the functionality to it).

**Comment by AtaTrkgl** [comment]
@caseycrogers Thank you, but I don't need it anymore.
